# Generated by Django 4.2.8 on 2024-01-02 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='updated_by',
        ),
    ]
